# Generated by Django 4.2.2 on 2023-06-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
